version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-devops
    ports:
      - "5672:5672"      # Porta do protocolo AMQP
      - "15672:15672"    # Painel de administração web
    environment:
      RABBITMQ_DEFAULT_USER: devops
      RABBITMQ_DEFAULT_PASS: devops